/** All copy here is review-only. Educational sheet bodies are labeled placeholders, not new content. */
export const foundationCopy = {
  review: 'HALO design review',
  status: 'Unapproved wireframes. Sample data only. No account, API requests or saved household changes.',
  scenario: 'Review a screen or state',
  appearance: 'Preview appearance',
  system: 'Follow device', light: 'Light', dark: 'Dark',
  scale: 'Text size', contrast: 'Higher contrast (proposed)', motion: 'Reduce motion',
  pageLabel: 'Shared foundation',
  sample: 'Shared component examples for design review.',
  shellHeading: 'One calm, consistent app',
  shellBody: 'Review the shared navigation and reading components here. Each page will use this same foundation.',
  notPage: (title: string) => `${title} content will be designed in its own stage. This view reviews the shared shell only.`,
  offline: "You're offline. Showing your last readings.",
  offlineEmpty: "You're offline. There are no stored readings to show yet.",
  stale: "Showing your last readings from 14 minutes ago. We couldn't reach the data source.",
  error: "We couldn't load your readings. Try again.",
  emptyHeading: 'Nothing here yet', emptyBody: 'Your saved items will appear here.',
  noDataBody: 'A reading is not available. Missing data is not a reassuring result.',
  retry: 'Try again', refreshing: 'Updating readings', refresh: 'Refresh example',
  continue: 'Continue', cancel: 'Cancel', save: 'Save changes', saved: 'Changes saved.',
  unavailable: 'Not available yet', destructive: 'Delete entry',
  deleteConfirm: 'Entry deleted.', dismissConfirm: 'Alert dismissed.', undo: 'Undo',
  restored: 'Entry restored.', replaceToast: 'Show another confirmation',
  buttonHeading: 'Buttons',
  readingExample: 'Sample reading', expanded: 'Reading detail',
  cardDetail: 'Full details appear here without leaving the page. Only one reading card is expanded at a time.',
  cardNoData: 'There is no reading available for this factor.',
  learn: 'What does this mean?',
  contribution: 'What contributes to the risk', noContribution: 'There is no risk to divide between factors in this sample.',
  full: 'Complete score', partial: 'Partial score', noData: 'No data',
  pills: 'Clear meaning, not color alone', provenance: 'Where a reading comes from', confidence: 'How complete a reading is',
  confidenceLabels: ['partial', '3+ yrs old', 'not evaluated'], provenanceLabels: ['measured', 'modeled', 'estimate'],
  confidenceNote: 'Full confidence has no pill. Unknown provenance has no pill. Today has no confidence field.',
  info: 'Info', caution: 'Caution', notice: 'Notice', errorTitle: 'Could not save',
  infoBody: 'This reading comes from a public source.',
  cautionBody: 'This is an estimate, not a measurement in your home.',
  noticeBody: 'Some readings are not available right now.',
  saveError: "We couldn't save your changes. Your answers are still here. Try again.",
  controls: 'Familiar controls', journalModes: ['Log', 'Trends'], renting: ['Owner', 'Renter'],
  groups: ['Toddlers', 'Children', 'Teens', 'Adults', 'Seniors', 'Pregnancy', 'Respiratory conditions'],
  toggleFailed: "We couldn't save that change. Your previous choice has been restored.",
  disabledNote: 'Household controls remain unavailable until the current profile has loaded.',
  accessibility: 'Accessibility', textSummary: 'Standard text', household: 'Household', optionalGroups: 'Optional. Choose any that apply.',
  switchLabel: 'Reduce motion', disabledSwitch: 'Device notifications (not available yet)',
  form: 'A form that keeps your answers', address: 'Address or ZIP code', year: 'Year your home was built',
  water: 'Water source', waterOptions: ['Choose a source', 'Public water system', 'Private well', 'Spring'],
  addressError: 'Enter an address or ZIP code.', yearError: 'Enter a four-digit year, or leave this blank.',
  futureError: "That year hasn't happened yet.", waterError: 'Choose where your water comes from.',
  note: 'Journal note', optional: 'Optional', noteHint: 'Up to 500 characters. The counter appears after 400.',
  checkbox: 'Illness flag', slider: 'Text size example', question: 'Assistant question',
  questionError: 'Ask a question to get started.', ask: 'Ask question',
  longAddress: '12345 Very Long Residential Street Extension, Apartment 1204, Concord, North Carolina 28025',
  spanish: 'Guardar los cambios de mi hogar',
  longTitle: 'A very long reading card title that remains accessible when expanded',
  longSummary: 'This is a deliberately long summary that wraps onto two lines before truncating, with its full text available on expansion.',
  swipeHeading: 'An action you can also reach', swipeBody: 'Swipe left or use the visible delete button. Undo stays available for eight seconds.',
  entry: 'September 29', entryNote: 'Sample journal note, displayed as plain text.',
  sheets: 'A sheet, not a new destination',
  standard: 'Open standard sheet', tall: 'Open tall sheet', compact: 'Open map detail',
  sheetTitles: { learn: 'Learn', alerts: 'Alerts', assistant: 'Luna', map: 'Water system' },
  sheetPlaceholder: 'Foundation placeholder. The full content and interactions will be designed in the corresponding page or sheet stage.',
  sheetNote: 'Close with Back, Escape, the close button, a backdrop tap or a downward drag. The page below stays in place.',
  replaceSheet: 'Replace with Learn', goToday: 'Go to Today', close: 'Close sheet',
  drag: 'Drag down to close sheet', yourReading: 'Your reading',
  genericLearn: 'This topic has no reading context on the current page.',
  unread: (n: number) => `Alerts, ${n} unread`, markRead: 'Read sample alert', markAll: 'Mark all as read',
  alert: 'Sample unread alert', alertBody: 'Reading this row changes the badge. Opening the sheet does not.',
  gateLoading: 'Checking your profile', gateIncomplete: 'Finish setting up your home',
  gateIncompleteBody: 'Your requested page will be kept while you complete onboarding.',
  gateLocation: 'Add your location', gateLocationBody: 'We need your location to load readings for your home.',
  gateError: "We couldn't check your profile. Try again.", setup: 'Continue setup example',
  unknownHeading: "This page isn't here", unknownBody: 'The link may have changed. Go back to Today.',
  identity: 'A recognizably HALO foundation', fonts: 'Headings and scores: Fraunces. Body and readings: Instrument Sans. Codes: IBM Plex Mono.',
  identityBody: 'The approved transparent mark stays the same. New shared surfaces and tokens are proposals for this review.',
  tokens: 'New shared token proposals', heroTokens: ['Morning', 'Midday', 'Evening', 'Night'],
  tokenBody: 'Today hero colors and house diagram colors are shown here as token studies, not page designs.',
  labels: {
    severity: 'Severity', inline: 'Inline messages', primary: 'Primary', secondary: 'Secondary and tertiary',
    availability: 'Loading and unavailable', destructive: 'Destructive and icon-only', settingsExample: 'Sample settings control',
    segments: 'Segmented controls', journalMode: 'Journal mode', tenure: 'Owner or renter', filter: 'Severity filter',
    filters: ['All', 'Elevated', 'Other'], switchStates: 'Switch states', enabledSwitch: 'Example enabled setting',
    sheetSizes: 'Sheet sizes', cardFamily: 'Card family', staticCard: 'Static card', tappableCard: 'Tappable card',
    loadingSheet: 'Loading sheet', loadingReadings: 'Loading readings', loadingDetail: 'Loading reading detail',
    dismiss: 'Dismiss', waterSystem: 'Sample water system', pfas: 'PFAS', air: 'Air quality',
    back: 'Back to previous page', settings: 'Settings', navigation: 'Main navigation', assistant: 'Ask Luna',
    numbers: 'Numbers never truncate', thresholdRows: 'Threshold rows', approvedLogo: 'Approved logo',
    logoAlt: 'HALO shield, house and leaf logo',
    tokenNames: ['Skeleton', 'Info', 'Caution', 'Notice', 'Limit marker', 'House ground', 'House roof'],
  },
  shortFactorLabels: { air: 'Air', uv: 'UV', pollen: 'Pollen', mold: 'Mold' } as Record<string, string>,
  ringLabel: (score: number, severity: string, partial: boolean) => `${partial ? 'Partial score' : 'Complete score'}: ${score}. ${severity}. Higher is better.`,
  factorLabel: (label: string, severity: string, share: number | null) => `${label}: ${severity === 'no_data' ? 'No data' : `${share}% of total risk`}. Expand reading.`,
  riskLabel: (risk: number, severity: string) => `Risk ${risk}, ${severity}`,
  bars: 'Comparable reading bars', risk: 'Risk bar', shownNotScored: 'shown, not scored', limit: 'Federal limit',
  thresholdNote: 'Scored rows use the same 0 to 2× limit scale. A value above 2× continues at the end.',
  pfas: 'Learn about PFAS', rawNormal: 'Server text is normalized before display, with no em dashes or raw database errors.',
} as const;
