import type { FactorKey } from '@/lib/frontend/factor-preview';
import { BookOpen, Info } from 'lucide-react';

const guides: Record<FactorKey, { title: string; boundary: string; question: string; answer: string; source: string; url: string }> = {
  air: { title: 'An outdoor signal, not an indoor test', boundary: 'A nearby monitor describes outdoor air. Your route, time outside, and indoor conditions can be different.', question: 'Why can one pollutant set the whole AQI?', answer: 'The reported AQI follows the pollutant with the highest index. It does not average a high reading away with cleaner readings for other pollutants.', source: 'AirNow: understanding AQI', url: 'https://www.airnow.gov/aqi/aqi-basics/' },
  uv: { title: 'The forecast is your guide, not the sky color', boundary: 'Scene lighting follows your clock. It does not change the UV forecast or tell you when sun protection is unnecessary.', question: 'What does the protection window mean?', answer: 'It is the period the supplied forecast reaches UV 3 or higher. Use it to plan shade and protective clothing. Cloudy weather does not eliminate UV exposure.', source: 'EPA: the UV Index', url: 'https://www.epa.gov/sunsafety/uv-index-scale-0' },
  pollen: { title: 'Different pollen, different days', boundary: 'An area forecast cannot identify your personal trigger. Tree, grass, and weed values remain separate so you can compare them with your own observations.', question: 'Why keep a note of symptoms?', answer: 'A record can help you discuss recurring symptoms with a clinician. Dates that line up with a pollen forecast do not prove what caused those symptoms.', source: 'CDC: pollen and your health', url: 'https://www.cdc.gov/climate-health/php/effects/pollen-health.html' },
  mold: { title: 'Look for moisture, not a prediction of mold', boundary: 'The mushrooms and drifting specks are an illustration of a damp environment. They are not detected mold, a spore count, or a picture of your home.', question: 'What is useful to check indoors?', answer: 'Look for leaks, condensation, and materials that stay damp. EPA recommends indoor humidity below 60%, ideally 30% to 50%. The outdoor forecast above cannot tell you your indoor humidity.', source: 'EPA: moisture and your home', url: 'https://www.epa.gov/mold/brief-guide-mold-moisture-and-your-home' },
  pfas: { title: 'A utility sample has a place and a date', boundary: 'The water illustration does not show contamination. These results describe the sampled water system, not a test taken at your tap today.', question: 'What should I check on a filter?', answer: 'Check the exact model and its certified PFAS-reduction claim, not just a generic certification logo. Follow replacement instructions. Certification is not a promise that every PFAS will be removed completely.', source: 'EPA: PFAS drinking-water information', url: 'https://www.epa.gov/sdwa/and-polyfluoroalkyl-substances-pfas' },
  radon: { title: 'County potential is not a home concentration', boundary: 'The house and ground are conceptual. No home radon test result is available here, and no scenery or county zone can supply one.', question: 'Does a lower-potential zone rule out radon?', answer: 'No. EPA recommends testing homes regardless of the county zone. A home test answers a different question from the area-level estimate shown here.', source: 'EPA: radon zones', url: 'https://www.epa.gov/radon/epa-map-radon-zones' },
  lead: { title: 'Building age is a clue, not a result', boundary: 'A home’s build year does not reveal every repair, pipe, or fixture. This estimate is kept separate from the score.', question: 'What would give a more specific answer?', answer: 'A water test and information about plumbing materials can help clarify the situation. Ask your water utility about its service-line information and use a certified laboratory for testing.', source: 'EPA: lead in drinking water', url: 'https://www.epa.gov/ground-water-and-drinking-water/basic-information-about-lead-drinking-water' },
};

export default function FactorReadingGuide({ factorKey }: { factorKey: FactorKey }) {
  const guide = guides[factorKey];
  return <div className="halo-reading-guide">
    <div className="halo-reading-boundary"><Info size={19} aria-hidden="true" /><div><h3>{guide.title}</h3><p>{guide.boundary}</p></div></div>
    <details><summary><BookOpen size={18} aria-hidden="true" /><span>{guide.question}</span><span className="halo-reading-open" aria-hidden="true">+</span></summary><p>{guide.answer}</p><a href={guide.url} target="_blank" rel="noopener noreferrer">{guide.source}</a></details>
  </div>;
}
